export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>
          <ul>
            <li>
              home
            </li>
          </ul>
        </nav>
        {children}
        
        
        </body>
    </html>
  )
}
